### ISSUE TITLE
Data Analysis

### ISSUE THREAD

**Issue by AliAlperenSonmez** [rburaksaritas/turkish-grammar-error-corrector-model#1]
- Elimizdeki datayı analiz etme, hangi yazım yanlışlarından ne kadar data point olduğunu tespit etme. 
- Yazım yanlışları için Data Format dokümanındaki başlıklar baz alınsın: 
   [Data Format Dokümanı](https://docs.google.com/document/d/1Z2wY9gk3iW7STv4OtwmudiFQNAboDDXHNJ7jbXgWX3U/edit?usp=sharing)
- Sonucu data format dokümanına başlık olarak açıp raporlayalım
- Sonraki adım olarak eksik datayı tamamlayacağımız aklımızda olsun.

**Comment by rburaksaritas** [comment]
very nicely done
