### ISSUE TITLE
Data tamamlama

### ISSUE THREAD

**Issue by AliAlperenSonmez** [rburaksaritas/turkish-grammar-error-corrector-model#2]
Based on my analysis, 800 data points are good for all data types. Yet, let's set our initial goal for 500 data points, for the following error types:

1-) Type 19:
num_samples: Trainset -> 3, devset -> 0, testset -> 1
definition: anlamı değişen isim tamlamaları birleşik yazılır.
examples: "kuş burnu"->"kuşburnu", "tavuk göğsü" -> "tavukgöğsü"
100 more examples will be enough for this type.

2-) Type 9:
num_samples: 304 in total
definition: filim, pırogram, tiren

3-) Type 15:
num_samples: 327
definition: kitapı, dolapı, kağıtı

**Comment by rburaksaritas** [comment]
lgtm
